07/03/2024 01:13:36 - INFO - __main__ - Logging setup complete.
07/03/2024 01:13:40 - ERROR - root - Map:   0%|          | 0/50 [00:00<?, ? examples/s]
07/03/2024 01:13:40 - ERROR - root - Map: 100%|##########| 50/50 [00:00<00:00, 1006.21 examples/s]
07/03/2024 01:13:40 - ERROR - root - /data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of ðŸ¤— Transformers. Use `eval_strategy` instead
  warnings.warn(
07/03/2024 01:13:40 - WARNING - accelerate.utils.other - Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
07/03/2024 01:13:41 - ERROR - root - /data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
07/03/2024 01:13:43 - ERROR - root -   0%|          | 0/4 [00:00<?, ?it/s]
07/03/2024 01:13:43 - ERROR - root -  50%|#####     | 2/4 [00:00<00:00, 12.19it/s]
07/03/2024 01:13:44 - ERROR - root - 100%|##########| 4/4 [00:00<00:00,  7.64it/s]
07/03/2024 01:13:44 - ERROR - root - 100%|##########| 4/4 [00:00<00:00,  8.07it/s]
07/03/2024 01:13:44 - ERROR - root - Traceback (most recent call last):
07/03/2024 01:13:44 - ERROR - root -   File "/home/jiaruil5/personality/llm_personality/llm_bigfive/classifier/classifier_inference_mse_newdata.py", line 98, in <module>
07/03/2024 01:13:44 - ERROR - root - convert_pred(predictions)
07/03/2024 01:13:44 - ERROR - root -   File "/home/jiaruil5/personality/llm_personality/llm_bigfive/classifier/classifier_inference_mse_newdata.py", line 58, in convert_pred
07/03/2024 01:13:44 - ERROR - root - preds = np.vstack([i.transpose() for i in pred.predictions[1:]]).transpose()
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root -   File "/home/jiaruil5/personality/llm_personality/llm_bigfive/classifier/classifier_inference_mse_newdata.py", line 58, in <listcomp>
07/03/2024 01:13:44 - ERROR - root - preds = np.vstack([i.transpose() for i in pred.predictions[1:]]).transpose()
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - ^
07/03/2024 01:13:44 - ERROR - root - AttributeError
07/03/2024 01:13:44 - ERROR - root - :
07/03/2024 01:13:44 - ERROR - root - 'list' object has no attribute 'transpose'
